spring:
  application:
    name: auth-service
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5168/auth_db
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000

server:
  port: 9000
  servlet:
    session:
      tracking-modes: cookie

logging.level.org.springframework.security: DEBUG
logging.level.org.springframework.security.oauth2.server.authorization: TRACE
logging.level.org.springframework.security.oauth2.server.authorization.oidc.authentication: TRACE

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}