services:
  bff-postgres:
    image: postgres:17.5-bullseye
    container_name: bff_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5168:5432"
    volumes:
      - bff-postgres-data:/var/lib/postgresql/data
    networks:
      - itp

# Create docker volume
volumes:
  bff-postgres-data:

# Bind network
networks:
  itp:
    external: true
