services:
  auth-postgres:
    image: postgres:17.5-bullseye
    container_name: auth_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5168:5432"
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
    networks:
      - itp

# Create docker volume
volumes:
  auth-postgres-data:

# Bind network
networks:
  itp:
    external: true
